project_id = "ephwmhikhiiyrnikvrwp"

[functions.generate-questions]
verify_jwt = false

[functions.get-assessment]
verify_jwt = false

[functions.submit-assessment]
verify_jwt = false

[functions.generate-group-narrative]
verify_jwt = true

[functions.generate-talent-snapshot]
verify_jwt = true

[functions.register-participant]
verify_jwt = false
